// prisma/seed-real.ts
// Import données réelles depuis le site officiel fleurieuxsurlarbresle.fr
// Sources : agenda mairie juin-août 2026, producteurs locaux, associations

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌐 Import données réelles...')

  // ── Catégories ───────────────────────────────
  const cats = await prisma.categorie.findMany()
  const cat = Object.fromEntries(cats.map(c => [c.slug, c.id]))

  // ── Nettoyage complet des données de démo ────
  await prisma.evenement.deleteMany({})
  await prisma.actu.deleteMany({})
  await prisma.avis.deleteMany({})
  await prisma.horaire.deleteMany({})
  await prisma.photo.deleteMany({})
  await prisma.tagActeur.deleteMany({})
  await prisma.acteur.deleteMany({})
  console.log('🗑  Toutes les données de démo supprimées')

  // ── Acteurs réels (source : mairie + site officiel) ─────────
  const acteurs = [
    // ── Producteurs locaux ────────────────────────
    {
      slug: 'jardin-fleurinois',
      nom: 'Le Jardin Fleurinois',
      emoji: '🥦',
      description: 'Légumes, fruits et volailles en vente directe à la ferme.',
      descriptionLongue: 'Catherine et David PERRELLE vous proposent leurs légumes, fruits et volailles issus de leur exploitation. Vente à la ferme, circuit court, qualité locale.',
      adresse: '41, Route A. Damez',
      telephone: '04 74 72 03 28',
      horairesNote: 'Lun-Ven 15h30-19h, Sam 9h-12h',
      categorieId: cat['producteurs-locaux'],
      statut: 'PUBLIE' as const,
      miseEnAvant: true,
    },
    {
      slug: 'marche-ferme-cueillettes',
      nom: 'Chez Chambe – Marché à la Ferme',
      emoji: '🍓',
      description: 'Fruits, légumes et produits locaux avec cueillette directe.',
      descriptionLongue: 'Catherine et Henry CHAMBE proposent fruits, légumes et produits locaux en vente directe. Possibilité de cueillette selon saison.',
      adresse: 'Route de Bel Air',
      telephone: '04 74 01 25 99',
      horairesNote: 'Lun-Jeu 15h30-19h, Ven 9h30-12h et 15h30-19h30, Sam 9h-12h',
      categorieId: cat['producteurs-locaux'],
      statut: 'PUBLIE' as const,
      miseEnAvant: true,
    },
    {
      slug: 'ferme-des-gones',
      nom: 'La Ferme des Gones',
      emoji: '🐄',
      description: 'Vente directe de viande de bœuf et ferme pédagogique.',
      descriptionLongue: 'Stéphane et Armelle CROZIER proposent de la viande de bœuf en vente directe depuis leur ferme. Ferme pédagogique pour accueillir les scolaires et les familles.',
      adresse: '2025 Route de France',
      telephone: '04 72 54 60 04',
      categorieId: cat['producteurs-locaux'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'saveurs-limousines',
      nom: 'Saveurs Limousines',
      emoji: '🥩',
      description: 'Vente directe de viande de bœuf limousin de qualité.',
      descriptionLongue: 'Jérôme et Sylvie CROZIER vous proposent de la viande de bœuf limousin élevé sur place, en vente directe à la ferme.',
      adresse: '24 Chemin du Buvet',
      telephone: '04 72 54 62 74',
      siteWeb: 'https://saveurs-limousines.com',
      categorieId: cat['producteurs-locaux'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'caveau-jomard-morillon',
      nom: 'Caveau Jomard – Le Morillon',
      emoji: '🍷',
      description: 'Vins Coteaux du Lyonnais, Beaujolais, jus de poire et eaux de vie.',
      descriptionLongue: 'JM JOMARD produit et vend ses vins des Coteaux du Lyonnais et du Beaujolais, ainsi que des jus de poire, de raisin et des eaux de vie artisanales.',
      adresse: '1057 Route Albert Damez',
      telephone: '04 74 01 02 27',
      categorieId: cat['producteurs-locaux'],
      statut: 'PUBLIE' as const,
      miseEnAvant: true,
    },
    {
      slug: 'rucher-macameli',
      nom: 'Le Rucher de Macameli',
      emoji: '🍯',
      description: 'Miel artisanal produit à Fleurieux, vente directe à la ruche.',
      descriptionLongue: 'Laurence et Fabien SCHOTS vous proposent leur miel artisanal issu de leurs ruches locales. Plusieurs variétés disponibles selon la saison.',
      adresse: '63, Chemin de Cassefroide',
      telephone: '04 78 20 01 76',
      horairesNote: 'Mar et Sam 9h-12h et 14h-18h30, Jeu et Ven 14h-18h30',
      categorieId: cat['producteurs-locaux'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'ferme-des-sources',
      nom: 'La Ferme des Sources',
      emoji: '🐐',
      description: 'Ferme auberge, fromages de chèvre et charcuterie maison.',
      descriptionLongue: 'La Ferme des Sources vous accueille pour découvrir ses fromages de chèvre artisanaux et ses charcuteries maison, dans un cadre authentique de ferme auberge.',
      telephone: '04 74 01 47 20',
      categorieId: cat['producteurs-locaux'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    // ── Commerces & Artisans ──────────────────────
    {
      slug: 'paradis-des-gourmands',
      nom: 'Au Paradis des Gourmands',
      emoji: '🥐',
      description: 'Boulangerie-pâtisserie artisanale au cœur du village.',
      descriptionLongue: 'Damien VINCENT vous accueille pour sa boulangerie-pâtisserie artisanale. Pains, viennoiseries, pâtisseries fraîches chaque jour.',
      adresse: '117, Place Benoît Dubost',
      telephone: '04 74 26 73 24',
      horairesNote: 'Mar-Ven 6h30-13h et 16h-19h30, Sam 6h30-13h et 16h-19h, Dim/Fériés 7h-12h30',
      categorieId: cat['commerces-artisans'],
      statut: 'PUBLIE' as const,
      miseEnAvant: true,
    },
    {
      slug: 'lidl-fleurieux',
      nom: 'LIDL',
      emoji: '🛒',
      description: 'Supermarché discount avec une large gamme de produits alimentaires.',
      descriptionLongue: 'Le LIDL de Fleurieux-sur-l\'Arbresle propose une large gamme de produits alimentaires et non alimentaires à prix discount.',
      adresse: 'Chemin du Cornu',
      telephone: '08 00 00 54 35',
      categorieId: cat['commerces-artisans'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'frais-et-compagnie',
      nom: 'Frais et Compagnie',
      emoji: '🥗',
      description: 'Alimentation de proximité, produits frais et épicerie.',
      descriptionLongue: 'Frais et Compagnie propose une sélection de produits frais, fruits et légumes et épicerie de proximité.',
      adresse: 'Chemin du Cornu',
      telephone: '04 74 01 59 41',
      categorieId: cat['commerces-artisans'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'carnet-botanique',
      nom: 'Carnet Botanique',
      emoji: '🌸',
      description: 'Atelier floral, compositions et créations botaniques artisanales.',
      descriptionLongue: 'Carnet Botanique vous propose des compositions florales, bouquets et créations végétales faites à la main au cœur du village.',
      adresse: '6, Place Benoît Dubost',
      horairesNote: 'Jeu-Sam 9h-13h et 15h-19h, Dim 9h-13h',
      categorieId: cat['commerces-artisans'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'tabac-le-phoenix',
      nom: 'Tabac le Phoenix',
      emoji: '📰',
      description: 'Bureau de tabac, presse, jeux et petite épicerie.',
      descriptionLongue: 'Le Tabac le Phoenix est votre point de vente de tabac, presse, jeux et petite épicerie de proximité au cœur de Fleurieux.',
      adresse: '6, Montée du Chêne',
      horairesNote: 'Lun/Mar/Jeu/Ven 6h30-14h et 16h-19h30, Sam 8h-14h et 16h-19h30, Dim 8h-12h30',
      categorieId: cat['commerces-artisans'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'la-centrale-bois',
      nom: 'La Centrale Bois',
      emoji: '🪵',
      description: 'Vente et livraison de bois de chauffage.',
      descriptionLongue: 'La Centrale Bois propose du bois de chauffage en stères et bûches, livré à domicile sur Fleurieux et les communes voisines.',
      adresse: 'Route de France',
      telephone: '04 74 01 20 23',
      categorieId: cat['commerces-artisans'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'garage-air',
      nom: 'Garage AIR',
      emoji: '🔧',
      description: 'Garage automobile toutes marques, entretien et réparation.',
      descriptionLongue: 'Le Garage AIR (Ivan Riondet) assure l\'entretien et la réparation de vos véhicules toutes marques.',
      adresse: '960 Chemin du Pinot',
      telephone: '04 74 01 28 61',
      categorieId: cat['commerces-artisans'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'otarie-carburant',
      nom: 'Otarie',
      emoji: '⛽',
      description: 'Station-service et carburant.',
      descriptionLongue: 'La station Otarie vous propose du carburant à Fleurieux-sur-l\'Arbresle, à proximité du LIDL.',
      adresse: 'Chemin du Cornu',
      categorieId: cat['commerces-artisans'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'bouticycle',
      nom: 'Bouticycle',
      emoji: '🚲',
      description: 'Vente, réparation et accessoires vélo.',
      descriptionLongue: 'Bouticycle est votre spécialiste local du vélo : vente de vélos neufs et d\'occasion, réparation et accessoires.',
      adresse: '69 Chemin du Cornu',
      categorieId: cat['commerces-artisans'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'clickn-office',
      nom: "Click'n Office",
      emoji: '🖨️',
      description: 'Assistante administrative indépendante, impression et fournitures.',
      descriptionLongue: "Click'n Office (Florence Lauret) propose des services d'assistance administrative indépendante, fournitures de bureau et services d'impression pour particuliers et professionnels.",
      adresse: '87, Place Benoît Dubost',
      telephone: '06 45 77 82 94',
      siteWeb: 'https://www.clickn-office.fr',
      categorieId: cat['commerces-artisans'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    // ── Restauration ─────────────────────────────
    {
      slug: 'bienvenue-chez-nous',
      nom: 'Bienvenue Chez Nous',
      emoji: '🍺',
      description: 'Bar restaurant au cœur de Fleurieux, ambiance conviviale.',
      descriptionLongue: 'Bienvenue Chez Nous vous accueille du matin au soir pour un café, un repas ou un verre dans une ambiance chaleureuse.',
      adresse: '37, Place des Deux Chouettes',
      telephone: '06 24 99 92 02',
      horairesNote: 'Lun-Mer 6h30-19h30, Jeu-Ven 6h30-23h, Sam 7h30-15h, Dim 8h-14h',
      categorieId: cat['restauration'],
      statut: 'PUBLIE' as const,
      miseEnAvant: true,
    },
    {
      slug: 'cambodge-gourmand',
      nom: 'Au Cambodge Gourmand',
      emoji: '🍜',
      description: 'Restaurant cambodgien, spécialités asiatiques maison.',
      descriptionLongue: 'Au Cambodge Gourmand vous invite à découvrir les saveurs authentiques de la cuisine cambodgienne préparée avec des produits frais.',
      adresse: '18, Place Benoît Dubost',
      telephone: '06 21 42 84 26',
      horairesNote: 'Mar-Mer déj. 11h-14h30, Jeu-Sam 11h-14h30 et 18h-22h30, Dim 11h-15h',
      categorieId: cat['restauration'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    // ── Santé & Bien-être ─────────────────────────
    {
      slug: 'belle-et-bio',
      nom: 'Belle et Bio',
      emoji: '💆',
      description: 'Institut de beauté, soins du visage et du corps.',
      descriptionLongue: 'Belle et Bio vous propose des soins de beauté naturels et biologiques pour le visage et le corps dans un cadre apaisant.',
      adresse: 'Chemin du Riboulet',
      telephone: '06 12 46 80 97',
      categorieId: cat['sante-bien-etre'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'kanittha-thai-massage',
      nom: 'Kanittha Thaï Massage',
      emoji: '🧘',
      description: 'Massages thaïlandais traditionnels, bien-être et relaxation.',
      descriptionLongue: 'Kanittha Thaï Massage propose des massages thaïlandais authentiques pour un moment de détente et de bien-être total.',
      adresse: '37, Place des Deux Chouettes',
      telephone: '06 14 69 87 57',
      siteWeb: 'https://www.kanitthathaimassage.com',
      categorieId: cat['sante-bien-etre'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'chantal-gery-energeticienne',
      nom: 'Chantal Géry Énergéticienne',
      emoji: '🌿',
      description: 'Soins énergétiques, numérologie et produits naturels aloe vera.',
      descriptionLongue: 'Chantal Géry vous accompagne avec des soins énergétiques, des séances de numérologie et des produits naturels à base d\'aloe vera.',
      adresse: '110, Rue Gabriel Combaudon',
      telephone: '06 17 29 62 26',
      siteWeb: 'https://www.chantal-at-home-energeticienne.fr',
      horairesNote: 'Lun-Ven 9h-19h, Sam 10h-13h',
      categorieId: cat['sante-bien-etre'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    // ── Associations ─────────────────────────────
    {
      slug: 'comite-des-fetes',
      nom: 'Comité des Fêtes',
      emoji: '🎉',
      description: 'Association qui organise les festivités et événements du village.',
      descriptionLongue: 'Le Comité des Fêtes de Fleurieux-sur-l\'Arbresle organise les grandes festivités locales tout au long de l\'année. Présidente : Corinne Astarik.',
      adresse: 'Place Benoît Dubost',
      telephone: '06 69 57 85 46',
      categorieId: cat['associations'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'afac',
      nom: 'AFAC',
      emoji: '💃',
      description: 'Association de sports et de danse pour tous les âges.',
      descriptionLongue: 'L\'AFAC propose des cours de danse et d\'activités sportives pour enfants et adultes, à la Place Benoît Dubost.',
      adresse: 'Place Benoît Dubost',
      categorieId: cat['associations'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'ajc-joggers-chouette',
      nom: 'AJC Joggers de la Chouette',
      emoji: '🏃',
      description: 'Club de course à pied et de jogging.',
      descriptionLongue: 'L\'AJC Joggers de la Chouette rassemble les passionnés de course à pied autour de sorties régulières et de compétitions locales.',
      telephone: '06 03 26 80 60',
      categorieId: cat['associations'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'amicale-donneurs-sang',
      nom: 'Amicale des Donneurs de Sang du Pays de l\'Arbresle',
      emoji: '🩸',
      description: 'Promotion et organisation des collectes de sang bénévoles.',
      descriptionLongue: 'L\'Amicale des Donneurs de Sang du Pays de l\'Arbresle organise et sensibilise à la pratique du don de sang, en partenariat avec l\'EFS.',
      categorieId: cat['associations'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'boule-du-vieux-coq',
      nom: 'Boule du Vieux Coq',
      emoji: '🎯',
      description: 'Club de boule lyonnaise et de pétanque.',
      descriptionLongue: 'La Boule du Vieux Coq anime la vie locale à travers des concours de boule lyonnaise et de pétanque ouverts à tous.',
      telephone: '04 74 26 72 01',
      categorieId: cat['associations'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'centre-jardinot',
      nom: 'Centre Jardinot',
      emoji: '🌳',
      description: 'Centre de loisirs et d\'animation pour les enfants et adolescents.',
      descriptionLongue: 'Le Centre Jardinot propose des activités de loisirs, d\'animation et de séjours pour les enfants et adolescents de la commune.',
      adresse: '226 Chemin du Pinot',
      categorieId: cat['associations'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'afatim-solidarite',
      nom: 'AFATIM Solidarité',
      emoji: '🤝',
      description: 'Association d\'aide au tiers monde et d\'actions humanitaires.',
      descriptionLongue: 'L\'AFATIM Solidarité mène des actions de solidarité internationale et d\'aide au développement dans les pays du tiers monde. Organise notamment les baptêmes side-car pour Haïti.',
      adresse: 'Fleurieux-sur-l\'Arbresle',
      categorieId: cat['associations'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    {
      slug: 'admr-lentilly',
      nom: 'ADMR',
      emoji: '🏠',
      description: 'Aide à domicile, ménage et services de proximité.',
      descriptionLongue: 'L\'ADMR propose des services d\'aide à domicile : aides ménagères, accompagnement et services de proximité pour les personnes dépendantes ou en perte d\'autonomie.',
      telephone: '06 66 99 71 47',
      categorieId: cat['associations'],
      statut: 'PUBLIE' as const,
      miseEnAvant: false,
    },
    // ── Services publics ──────────────────────────
    {
      slug: 'mairie-fleurieux',
      nom: 'Mairie de Fleurieux',
      emoji: '🏛️',
      description: 'Service municipal, état civil, urbanisme et démarches administratives.',
      descriptionLongue: 'La Mairie de Fleurieux-sur-l\'Arbresle assure les services publics de la commune : état civil, urbanisme, démarches administratives. Maire : Diogène BATALLA.',
      adresse: '21, Place Benoît Dubost',
      telephone: '04 74 01 26 01',
      siteWeb: 'https://www.fleurieuxsurlarbresle.fr',
      categorieId: cat['services-publics'],
      statut: 'PUBLIE' as const,
      miseEnAvant: true,
    },
  ]

  for (const acteur of acteurs) {
    await prisma.acteur.upsert({
      where: { slug: acteur.slug },
      update: acteur,
      create: acteur,
    })
  }
  console.log(`✅ ${acteurs.length} acteurs réels importés`)

  // ── Événements réels (source : agenda mairie) ──────────────
  const evenements = [
    {
      slug: 'don-de-sang-juin-2026',
      titre: 'Don de sang',
      description: 'Collecte de sang organisée par l\'EFS. Venez donner et sauver des vies !',
      dateDebut: new Date('2026-06-09T09:00:00'),
      dateFin: new Date('2026-06-09T19:00:00'),
      lieu: 'Centre-ville',
      adresse: "L'Arbresle",
      gratuit: true,
      sourceUrl: 'https://www.fleurieuxsurlarbresle.fr/fr/ev/714235/1769029/don-de-sang-72',
      statut: 'PUBLIE' as const,
    },
    {
      slug: 'ball-trap-juin-2026',
      titre: 'Ball Trap',
      description: 'Compétition de ball-trap ouverte à tous les niveaux.',
      dateDebut: new Date('2026-06-12T09:00:00'),
      dateFin: new Date('2026-06-14T18:00:00'),
      lieu: 'Fleurieux-sur-l\'Arbresle',
      gratuit: false,
      prix: 'Tarif à confirmer',
      sourceUrl: 'https://www.fleurieuxsurlarbresle.fr/fr/ev/714235/1912406/ball-trap-17',
      statut: 'PUBLIE' as const,
    },
    {
      slug: 'gala-de-danse-juin-2026',
      titre: 'Gala de Danse',
      description: 'Spectacle de fin d\'année des cours de danse locaux.',
      dateDebut: new Date('2026-06-13T18:30:00'),
      lieu: 'Fleurieux-sur-l\'Arbresle',
      gratuit: false,
      prix: '8 €',
      sourceUrl: 'https://www.fleurieuxsurlarbresle.fr/fr/ev/714235/1919192/gala-de-danse-24',
      statut: 'PUBLIE' as const,
    },
    {
      slug: 'baptemes-sidecar-haiti-2026',
      titre: 'Baptêmes Side-Car pour Haïti',
      description: 'Baptêmes en side-car au profit d\'Haïti, organisés par l\'AFATIM. Une belle façon de soutenir une cause humanitaire tout en vivant une expérience unique.',
      dateDebut: new Date('2026-06-14T10:00:00'),
      dateFin: new Date('2026-06-14T17:00:00'),
      lieu: 'Fleurieux-sur-l\'Arbresle',
      gratuit: false,
      prix: 'Participation aux frais',
      sourceUrl: 'https://www.fleurieuxsurlarbresle.fr/fr/ev/714235/1921597/baptemes-side-car-pour-haiti-2',
      statut: 'PUBLIE' as const,
    },
    {
      slug: 'fete-de-lete-2026',
      titre: 'Fête de l\'Été',
      description: 'Grande fête estivale du village organisée par le Comité des Fêtes. Animations, musique et convivialité au programme.',
      dateDebut: new Date('2026-06-19T19:00:00'),
      lieu: 'Place Benoît Dubost',
      adresse: 'Fleurieux-sur-l\'Arbresle',
      gratuit: true,
      sourceUrl: 'https://www.fleurieuxsurlarbresle.fr/fr/ev/714235/1914655/fete-de-l-ete-5',
      statut: 'PUBLIE' as const,
    },
    {
      slug: 'decouverte-patrimoine-fleurinois-2026',
      titre: 'Découverte du Patrimoine Fleurinois',
      description: 'Balade guidée à la découverte du patrimoine architectural et naturel de Fleurieux. Réservation conseillée.',
      dateDebut: new Date('2026-06-20T09:30:00'),
      dateFin: new Date('2026-06-20T12:30:00'),
      lieu: 'Départ Mairie',
      adresse: 'Place Benoît Dubost, Fleurieux-sur-l\'Arbresle',
      gratuit: false,
      prix: '10 €',
      sourceUrl: 'https://www.fleurieuxsurlarbresle.fr/fr/ev/714235/1919205/decouverte-du-patrimoine-fleurinois',
      statut: 'PUBLIE' as const,
    },
    {
      slug: 'conseil-municipal-juillet-2026',
      titre: 'Conseil Municipal',
      description: 'Séance publique du Conseil Municipal. Ouvert à tous les habitants.',
      dateDebut: new Date('2026-07-06T20:00:00'),
      lieu: 'Mairie de Fleurieux',
      adresse: '21, Place Benoît Dubost',
      gratuit: true,
      sourceUrl: 'https://www.fleurieuxsurlarbresle.fr/fr/ev/714235/1895428/conseil-municipal-976',
      statut: 'PUBLIE' as const,
    },
    {
      slug: 'fete-nationale-2026',
      titre: 'Fête Nationale',
      description: 'Célébration du 14 juillet avec le Comité des Fêtes. Feu d\'artifice, musique et vin d\'honneur.',
      dateDebut: new Date('2026-07-13T19:00:00'),
      lieu: 'Place Benoît Dubost',
      adresse: 'Fleurieux-sur-l\'Arbresle',
      gratuit: true,
      sourceUrl: 'https://www.fleurieuxsurlarbresle.fr/fr/ev/714235/1914668/fete-nationale-54',
      statut: 'PUBLIE' as const,
    },
    {
      slug: 'don-de-sang-juillet-2026',
      titre: 'Don de sang',
      description: 'Collecte de sang de l\'EFS. Chaque don peut sauver jusqu\'à 3 vies.',
      dateDebut: new Date('2026-07-17T09:00:00'),
      dateFin: new Date('2026-07-17T13:00:00'),
      lieu: 'Centre-ville',
      adresse: "L'Arbresle",
      gratuit: true,
      sourceUrl: 'https://www.fleurieuxsurlarbresle.fr/fr/ev/714235/1859106/don-de-sang-105',
      statut: 'PUBLIE' as const,
    },
    {
      slug: 'don-de-sang-aout-2026',
      titre: 'Don de sang',
      description: 'Collecte de sang de l\'EFS.',
      dateDebut: new Date('2026-08-17T09:00:00'),
      dateFin: new Date('2026-08-17T13:00:00'),
      lieu: 'Centre-ville',
      adresse: "L'Arbresle",
      gratuit: true,
      sourceUrl: 'https://www.fleurieuxsurlarbresle.fr/fr/ev/714235/1859119/don-de-sang-106',
      statut: 'PUBLIE' as const,
    },
  ]

  for (const ev of evenements) {
    await prisma.evenement.upsert({
      where: { slug: ev.slug },
      update: ev,
      create: ev,
    })
  }
  console.log(`✅ ${evenements.length} événements réels importés`)

  // ── Actualités ───────────────────────────────
  const actus = [
    {
      slug: 'elections-municipales-2026-resultats',
      titre: 'Élections municipales 2026 : résultats',
      contenu: 'Les élections municipales de 2026 ont eu lieu. Diogène BATALLA est le maire de Fleurieux-sur-l\'Arbresle. Le nouveau conseil municipal se réunira prochainement.',
      source: 'Mairie',
      statut: 'PUBLIE' as const,
      publishedAt: new Date('2026-03-30T12:00:00'),
    },
    {
      slug: 'revision-plu-2026',
      titre: 'Révision du Plan Local d\'Urbanisme (PLU) en cours',
      contenu: 'La commune engage la révision de son PLU. Les habitants sont invités à participer aux réunions de concertation. Renseignements en mairie au 04 74 01 26 01.',
      source: 'Mairie',
      statut: 'PUBLIE' as const,
      publishedAt: new Date('2026-04-15T09:00:00'),
    },
    {
      slug: 'recrutement-commune-2026',
      titre: 'La commune recrute',
      contenu: 'Fleurieux-sur-l\'Arbresle recrute : accompagnateur périscolaire, ATSEM et agent d\'animation. Candidatures à adresser en mairie. Renseignements : accueil@mairie-fleurieux.fr',
      source: 'Mairie',
      statut: 'PUBLIE' as const,
      publishedAt: new Date('2026-05-10T08:00:00'),
    },
    {
      slug: 'fete-ete-programme-2026',
      titre: 'Programme de la Fête de l\'Été le 19 juin',
      contenu: 'Le Comité des Fêtes organise la Fête de l\'Été le 19 juin à partir de 19h, Place Benoît Dubost. Animations musicales, buvette et restauration sur place. Entrée gratuite, venez nombreux !',
      source: 'Comité des Fêtes',
      statut: 'PUBLIE' as const,
      publishedAt: new Date('2026-06-01T10:00:00'),
    },
    {
      slug: 'patrimoine-balade-juin-2026',
      titre: 'Balade patrimoine : inscrivez-vous !',
      contenu: 'Une découverte guidée du patrimoine fleurinois est organisée le 20 juin (9h30-12h30). Tarif : 10€. Places limitées. Inscription en mairie ou par téléphone au 04 74 01 26 01.',
      source: 'Mairie',
      statut: 'PUBLIE' as const,
      publishedAt: new Date('2026-06-05T08:00:00'),
    },
  ]

  for (const actu of actus) {
    await prisma.actu.upsert({
      where: { slug: actu.slug },
      update: actu,
      create: actu,
    })
  }
  console.log(`✅ ${actus.length} actualités importées`)

  console.log('\n🎉 Import données réelles terminé !')
  console.log('   Source : fleurieuxsurlarbresle.fr (agenda + producteurs locaux)')
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
